; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2428	DB	'hello, world', 0aH, 00H
_DATA	ENDS
PUBLIC	main
EXTRN	__imp_printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+24
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
; Function compile flags: /Odtp
xdata	ENDS
_TEXT	SEGMENT
main	PROC
; File c:\users\user\desktop\binaries\03_hello_world.c
; Line 7
$LN3:
	sub	rsp, 40					; 00000028H
; Line 8
	lea	rcx, OFFSET FLAT:$SG2428
	call	QWORD PTR __imp_printf
; Line 9
	xor	eax, eax
; Line 10
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
