; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	C:\Users\user\Desktop\binaries\03_hello_world.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2469	DB	'hello, world', 0aH, 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\users\user\desktop\binaries\03_hello_world.c
; Line 7
	push	ebp
	mov	ebp, esp
; Line 8
	push	OFFSET $SG2469
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 9
	xor	eax, eax
; Line 10
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
