; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	C:\Users\user\Desktop\binaries\04_hello_world_const.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_$SG7386
CONST	SEGMENT
_$SG7386 DB	'hello, world', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\users\user\desktop\binaries\04_hello_world_const.c
; Line 8
	push	ebp
	mov	ebp, esp
; Line 9
	push	OFFSET _$SG7386
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 10
	xor	eax, eax
; Line 11
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
