; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	C:\Users\user\Desktop\binaries\05_stack_args.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2472	DB	'%d, %d, %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_c$ = -12						; size = 4
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_main	PROC
; File c:\users\user\desktop\binaries\05_stack_args.c
; Line 6
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 7
	mov	DWORD PTR _a$[ebp], 1
; Line 8
	mov	DWORD PTR _b$[ebp], 2
; Line 9
	mov	DWORD PTR _c$[ebp], 3
; Line 10
	mov	eax, DWORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _b$[ebp]
	push	ecx
	mov	edx, DWORD PTR _a$[ebp]
	push	edx
	push	OFFSET $SG2472
	call	DWORD PTR __imp__printf
	add	esp, 16					; 00000010H
; Line 11
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
