; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2429	DB	'Enter X:', 0aH, 00H
	ORG $+2
$SG2430	DB	'%d', 00H
	ORG $+1
$SG2431	DB	'You entered %d...', 0aH, 00H
_DATA	ENDS
PUBLIC	main
EXTRN	__imp_scanf:PROC
EXTRN	__imp_printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+58
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
; Function compile flags: /Odtp
xdata	ENDS
_TEXT	SEGMENT
x$ = 32
main	PROC
; File c:\users\user\desktop\binaries\11_scanf.c
; Line 7
$LN3:
	sub	rsp, 56					; 00000038H
; Line 9
	lea	rcx, OFFSET FLAT:$SG2429
	call	QWORD PTR __imp_printf
; Line 10
	mov	edx, DWORD PTR x$[rsp]
	lea	rcx, OFFSET FLAT:$SG2430
	call	QWORD PTR __imp_scanf
; Line 11
	mov	edx, DWORD PTR x$[rsp]
	lea	rcx, OFFSET FLAT:$SG2431
	call	QWORD PTR __imp_printf
; Line 12
	xor	eax, eax
; Line 13
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
END
