; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2429	DB	'Enter X:', 0aH, 00H
	ORG $+2
$SG2431	DB	'%d', 00H
	ORG $+1
$SG2432	DB	'You entered %d...', 0aH, 00H
	ORG $+1
$SG2434	DB	'woof.', 0aH, 00H
_DATA	ENDS
PUBLIC	main
EXTRN	__imp_scanf:PROC
EXTRN	__imp_printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN5
	DD	imagerel $LN5+79
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
; Function compile flags: /Odtp
xdata	ENDS
_TEXT	SEGMENT
x$ = 32
main	PROC
; File c:\users\user\desktop\binaries\14_scanf_error_check.c
; Line 6
$LN5:
	sub	rsp, 56					; 00000038H
; Line 8
	lea	rcx, OFFSET FLAT:$SG2429
	call	QWORD PTR __imp_printf
; Line 10
	lea	rdx, QWORD PTR x$[rsp]
	lea	rcx, OFFSET FLAT:$SG2431
	call	QWORD PTR __imp_scanf
	cmp	eax, 1
	jne	SHORT $LN2@main
; Line 11
	mov	edx, DWORD PTR x$[rsp]
	lea	rcx, OFFSET FLAT:$SG2432
	call	QWORD PTR __imp_printf
; Line 12
	jmp	SHORT $LN1@main
$LN2@main:
; Line 13
	lea	rcx, OFFSET FLAT:$SG2434
	call	QWORD PTR __imp_printf
$LN1@main:
; Line 14
	xor	eax, eax
; Line 15
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
END
