; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\admin\Desktop\git\binaries\22_conditional_jumps.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2473	DB	'a>b', 0aH, 00H
	ORG $+3
$SG2475	DB	'a==b', 0aH, 00H
	ORG $+2
$SG2477	DB	'a<b', 0aH, 00H
	ORG $+3
$SG2485	DB	'a>b', 0aH, 00H
	ORG $+3
$SG2487	DB	'a==b', 0aH, 00H
	ORG $+2
$SG2489	DB	'a<b', 0aH, 00H
_DATA	ENDS
PUBLIC	_f_signed
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_f_signed PROC
; File c:\users\admin\desktop\git\binaries\22_conditional_jumps.c
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	mov	eax, DWORD PTR _a$[ebp]
	cmp	eax, DWORD PTR _b$[ebp]
	jle	SHORT $LN3@f_signed
; Line 8
	push	OFFSET $SG2473
	call	_printf
	add	esp, 4
$LN3@f_signed:
; Line 9
	mov	ecx, DWORD PTR _a$[ebp]
	cmp	ecx, DWORD PTR _b$[ebp]
	jne	SHORT $LN2@f_signed
; Line 10
	push	OFFSET $SG2475
	call	_printf
	add	esp, 4
$LN2@f_signed:
; Line 11
	mov	edx, DWORD PTR _a$[ebp]
	cmp	edx, DWORD PTR _b$[ebp]
	jge	SHORT $LN4@f_signed
; Line 12
	push	OFFSET $SG2477
	call	_printf
	add	esp, 4
$LN4@f_signed:
; Line 13
	pop	ebp
	ret	0
_f_signed ENDP
_TEXT	ENDS
PUBLIC	_f_unsigned
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_f_unsigned PROC
; Line 15
	push	ebp
	mov	ebp, esp
; Line 16
	mov	eax, DWORD PTR _a$[ebp]
	cmp	eax, DWORD PTR _b$[ebp]
	jbe	SHORT $LN3@f_unsigned
; Line 17
	push	OFFSET $SG2485
	call	_printf
	add	esp, 4
$LN3@f_unsigned:
; Line 18
	mov	ecx, DWORD PTR _a$[ebp]
	cmp	ecx, DWORD PTR _b$[ebp]
	jne	SHORT $LN2@f_unsigned
; Line 19
	push	OFFSET $SG2487
	call	_printf
	add	esp, 4
$LN2@f_unsigned:
; Line 20
	mov	edx, DWORD PTR _a$[ebp]
	cmp	edx, DWORD PTR _b$[ebp]
	jae	SHORT $LN4@f_unsigned
; Line 21
	push	OFFSET $SG2489
	call	_printf
	add	esp, 4
$LN4@f_unsigned:
; Line 22
	pop	ebp
	ret	0
_f_unsigned ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 23
	push	ebp
	mov	ebp, esp
; Line 24
	push	2
	push	1
	call	_f_signed
	add	esp, 8
; Line 25
	push	2
	push	1
	call	_f_unsigned
	add	esp, 8
; Line 26
	xor	eax, eax
; Line 27
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
