; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\admin\Desktop\binaries\23_switch_case_sw.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2476	DB	'zero', 0aH, 00H
	ORG $+2
$SG2478	DB	'one', 0aH, 00H
	ORG $+3
$SG2480	DB	'two', 0aH, 00H
	ORG $+3
$SG2482	DB	'something unknown', 0aH, 00H
_DATA	ENDS
PUBLIC	_f
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv64 = -4						; size = 4
_a$ = 8							; size = 4
_f	PROC
; File c:\users\admin\desktop\binaries\23_switch_case_sw.c
; Line 6
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 7
	mov	eax, DWORD PTR _a$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 0
	je	SHORT $LN4@f
	cmp	DWORD PTR tv64[ebp], 1
	je	SHORT $LN3@f
	cmp	DWORD PTR tv64[ebp], 2
	je	SHORT $LN2@f
	jmp	SHORT $LN1@f
$LN4@f:
; Line 9
	push	OFFSET $SG2476
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 10
	jmp	SHORT $LN7@f
$LN3@f:
; Line 11
	push	OFFSET $SG2478
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 12
	jmp	SHORT $LN7@f
$LN2@f:
; Line 13
	push	OFFSET $SG2480
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 14
	jmp	SHORT $LN7@f
$LN1@f:
; Line 15
	push	OFFSET $SG2482
	call	DWORD PTR __imp__printf
	add	esp, 4
$LN7@f:
; Line 18
	mov	esp, ebp
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 20
	push	ebp
	mov	ebp, esp
; Line 21
	push	2
	call	_f
	add	esp, 4
; Line 22
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
