; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\user\Desktop\binaries\23_switch_case.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2518	DB	'zero', 0aH, 00H
	ORG $+2
$SG2521	DB	'one', 0aH, 00H
	ORG $+3
$SG2524	DB	'two', 0aH, 00H
	ORG $+3
$SG2526	DB	'something unknown', 0aH, 00H
_DATA	ENDS
PUBLIC	_f
EXTRN	__imp__printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 4
_f	PROC
; File c:\users\user\desktop\binaries\23_switch_case.c
; Line 7
	mov	eax, DWORD PTR _a$[esp-4]
	test	eax, eax
	jne	SHORT $LN6@f
; Line 8
	mov	DWORD PTR _a$[esp-4], OFFSET $SG2518
	jmp	DWORD PTR __imp__printf
$LN6@f:
; Line 9
	cmp	eax, 1
	jne	SHORT $LN4@f
; Line 10
	mov	DWORD PTR _a$[esp-4], OFFSET $SG2521
	jmp	DWORD PTR __imp__printf
$LN4@f:
; Line 11
	cmp	eax, 2
	jne	SHORT $LN2@f
; Line 12
	mov	DWORD PTR _a$[esp-4], OFFSET $SG2524
	jmp	DWORD PTR __imp__printf
$LN2@f:
; Line 14
	mov	DWORD PTR _a$[esp-4], OFFSET $SG2526
	jmp	DWORD PTR __imp__printf
_f	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 18
	push	OFFSET $SG2524
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 19
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
