; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\user\Desktop\binaries\24_for_loops.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2517	DB	'f(%d)', 0aH, 00H
_DATA	ENDS
PUBLIC	_printing_function
EXTRN	__imp__printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
_printing_function PROC
; File c:\users\user\desktop\binaries\24_for_loops.c
; Line 8
	mov	eax, DWORD PTR _i$[esp-4]
	push	eax
	push	OFFSET $SG2517
	call	DWORD PTR __imp__printf
	add	esp, 8
; Line 9
	ret	0
_printing_function ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; Line 11
	push	esi
	push	edi
; Line 13
	mov	edi, DWORD PTR __imp__printf
	mov	esi, 2
	npad	3
$LL3@main:
; Line 14
	push	esi
	push	OFFSET $SG2517
	call	edi
	inc	esi
	add	esp, 8
	cmp	esi, 10					; 0000000aH
	jl	SHORT $LL3@main
	pop	edi
; Line 15
	xor	eax, eax
	pop	esi
; Line 16
	ret	0
_main	ENDP
_TEXT	ENDS
END
