; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\user\Desktop\binaries\28_buffer_overflow.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2474	DB	'a[20]=%d', 0aH, 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = -84						; size = 4
_a$ = -80						; size = 80
_main	PROC
; File c:\users\user\desktop\binaries\28_buffer_overflow.c
; Line 5
	push	ebp
	mov	ebp, esp
	sub	esp, 84					; 00000054H
; Line 8
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN3@main
$LN2@main:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN3@main:
	cmp	DWORD PTR _i$[ebp], 20			; 00000014H
	jge	SHORT $LN1@main
; Line 9
	mov	ecx, DWORD PTR _i$[ebp]
	shl	ecx, 1
	mov	edx, DWORD PTR _i$[ebp]
	mov	DWORD PTR _a$[ebp+edx*4], ecx
	jmp	SHORT $LN2@main
$LN1@main:
; Line 10
	mov	eax, DWORD PTR _a$[ebp+80]
	push	eax
	push	OFFSET $SG2474
	call	DWORD PTR __imp__printf
	add	esp, 8
; Line 11
	xor	eax, eax
; Line 12
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
